### ISSUE TITLE
reposync --verify package checksum

### ISSUE THREAD

**Issue by rothgar** [rpm-software-management/yum-utils#24] opened 2017-07-06 18:22 UTC
Is there a way we could add a flag to reposync to verify the file downloaded properly from the source repository? The md5 and sha checksums are already available from the source repository but I frequently get download errors that leave zero byte files ore 1/2 downloaded files with errors. I have to manually check these files after download, delete bad files, and run reposync again.

It would be great if reposync had a way to verify the downloaded files similar to `rsync --checksum`

**Comment by alexsons** [comment] 2017-11-01 12:33
This would be a great added feature. I am dealing with a similar situation at work. Mirroring a repository that occasionally has incomplete file downloads. Subsequent, reposync runs don't compare the existing file to the source. IMHO, this is a pretty big feature to not have in a repository syncing tool. Not only for incomplete or corrupted files, but also to correct/undo any altering of the files on the mirrored repository.

Please add this functionality.

**Comment by rothgar** [comment] 2017-11-01 16:56
@alexsons I created my own tool to verify synced files from an upstream source. I'm going through my work's process to open source it and if/when it is open sourced I'll post a link to it here.

**Comment by dmnks** [comment] 2017-11-09 15:19
Actually, this is already done. `reposync` uses `YumBase.downloadPkgs()` to download packages and this method also verifies their checksums after the fact. Is that not working for you, or am I missing something?

**Comment by rothgar** [comment] 2017-11-09 15:27
It definitely does not work for me. I sync ~150 repos weekly and frequently have partial or failed files left in the repo after a sync.

The tool I created will re-verify the hashes and often re-downloads anywhere from 2-20 rpms on large repos (epel, fedora, etc.)

**Comment by dmnks** [comment] 2017-11-09 16:41
OK, I see your point now. The thing is, `reposync` does attempt to resume the download of a failed package when it detects the actual checksum doesn't match the expected one (this is done 10 times by default). However, I can think of two cases where this wouldn't help:

A) you hit some intermittent problem with the server so the repeated attempts all fail and you have to re-run `reposync` a few moments later in order to get the valid packages, or

B) you hit a urlgrabber bug that involves sending a malformed `Range` header in the HTTP request, which causes the `416 Range Not Satisfiable` response from the server, which in turn causes urlgrabber to stop any further attempts to resume the failed download (I will have to dig into this one and maybe fix it).

That said, it's great that you solved this with your own tool so don't hesitate to link it here once approved :)

**Comment by dmnks** [comment] 2017-11-09 17:17
I just looked at B) more closely and it seems there's no such bug after all (the malformed `Range` header and the `416` response aren't related to this problem). If the package is correct on the server, urlgrabber should indeed finish the file successfully during the repeated attempt(s).

**Comment by rothgar** [comment] 2017-11-09 17:27
Is there a way to debug why that isn't happening? I frequently get 0 byte files and 1/2 downloaded rpms

**Comment by dmnks** [comment] 2017-11-09 17:30
You can try running reposync with the URLGRABBER_DEBUG=1 env var. It would be great if you could capture the stdout & stderr and post it to pastebin.com (but be wary that this may be a HUGE dump if you sync the whole repo).

**Comment by dmnks** [comment] 2017-11-09 17:32
BTW, one more possibility I forgot to mention:

C) reposync downloads corrupt data that's less in size than the expected file, in which case it still treats it as an incomplete download and tries to resume it, which obviously won't produce the correct file either (this could be fixed in reposync I think).

**Comment by shai** [comment] 2017-11-16 11:38
+1 to what @rothgar is saying. I've having these exact same issues. I'm checking the md5 of the files on the remote repo and the files that has been downloaded and I see that they are not the same.

**Comment by shai** [comment] 2017-11-16 11:41
For the sake of the test, I went into yumRepo.py and set all instance of 'reget' variable to None. This caused urlgrabber to not even try to resume RPMs that are not complete or not the same size. Simply download them and be done with it. This worked of course but it's far from an ideal solution but rather a quick and dirty workaround.

**Comment by shai** [comment] 2017-11-16 12:06
@rothgar how do you recognize FAILED downloads via reposync to be downloaded later using your custom tool?

**Comment by rothgar** [comment] 2017-11-16 18:35
My tool takes an source url and a directory (or single file) to check. It fetches the primary.xml from the source repo and saves it as a hash to know the package name, path, and hash. It then walks the local directory, hashes each file, and compares them with what the source had.
Optionally you can delete the local file and redownload (-d flag) or just check the files and it'll print out all the files that don't have matching hashes.
I'll ask my legal team what the status of this is so I can get it released.

**Comment by shai** [comment] 2017-11-16 18:43
@rothgar thank you! I'll look forward to hearing good news *cross fingers* :)

**Comment by rothgar** [comment] 2018-01-08 07:48
@dmnks I've been running with URLGRABBER_DEBUG=1 set on my syncs but haven't had time to go back through and find files failing to download to see what the logs show. I'll try to get back to that sometime so I can see why they're failing.

**Comment by shai** [comment] 2018-01-08 08:14
@rothgar thanks! I tried to access this repository but got 

> The page could not be found or you don't have permission to view it.

**Comment by rothgar** [comment] 2018-01-08 14:44
Sorry, It's a private repo.

**Comment by alphacc** [comment] 2018-02-15 16:14
We witnessed the same issue, do you need  the URLGRABBER_DEBUG=1 trace or you got some already ?

**Comment by dmnks** [comment] 2018-02-20 14:26
We haven't. If you can obtain it, it might be useful, thanks.

**Comment by alphacc** [comment] 2018-03-09 15:18
Hi, attaching the trace.
[reposync.log](https://github.com/rpm-software-management/yum-utils/files/1797348/reposync.log)

**Comment by dmnks** [comment] 2018-03-13 15:28
@alphacc Thanks, I've looked at it and saw this:

```
[...]
2018-03-09 13:56:16,949 exception: [Errno 14] PYCURL ERROR 18 - "transfer closed with 30291384 bytes remaining to read"
2018-03-09 13:56:16,951 retrycode (14) not in list [-1, 2, 4, 5, 6, 7], re-raising
2018-03-09 13:56:16,952 MIRROR: failed
2018-03-09 13:56:16,952 GR   mirrors: [] 0
2018-03-09 13:56:16,952 MAIN mirrors: [http://debuginfo.centos.org/7/i386/] 0
Could not retrieve package gcc-debuginfo-4.8.5-16.el7_4.2.i686. Error was failure: gcc-debuginfo-4.8.5-16.el7_4.2.i686.rpm from centosdebug-7-os-i386: [Errno 256] No more mirrors to try.
2018-03-09 13:56:17,148 MIRROR: trying libreoffice-debuginfo-5.0.6.2-15.el7_4.i686.rpm -> http://debuginfo.centos.org/7/i386/libreoffice-debuginfo-5.0.6.2-15.el7_4.i686.rpm
[...]
```

That indicates there had been an error during the download which didn't fall into the category of errors after which urlgrabber would activate the retry loop (10 attempts by default). This list is hardcoded by default and can be modified arbitrarily by the caller, but yum just sticks with the default and does not offer any option to configure it either. Whether that's good or bad is up for discussion.

Nevertheless, when this happens, re-running reposync should pick up where it left and finish the incomplete packages. The problem is, there's no easy way to crawl the sync directory after the fact and find out if there are any incomplete downloads. This is something that could be added to reposync for sure.

As a workaround, the script provided by @rothgar may be a good solution, esp. if you use reposync in your own scripts.

**Comment by dmnks** [comment] 2018-03-13 16:44
> The problem is, there's no easy way to crawl the sync directory after the fact and find out if there are any incomplete downloads. This is something that could be added to reposync for sure.

Actually, I realized that you can use `verifytree` to do exactly this. The annoyance is that you have to create a valid repo out of the directory where you synced the packages; that's basically creating a `repodata/` subdir next to `Packages/` and copying in `repomd.xml` and all the metadata files it references from the yum cache.

Then you just run:
`verifytree -a file:///path/to/repo/ 2>/dev/null | grep FAILED`
which prints all packages that don't match the expected checksum.

**Comment by rothgar** [comment] 2018-03-13 20:21
@dmnks my `check-rpm` script verifys a directory of rpms against a source repository.

It has a couple known bugs I'm working on but works in most cases for my needs right now.

**Comment by dmnks** [comment] 2018-03-14 09:41
@rothgar yup, the `verifytree` way I mentioned was just for the sake of completeness. Since it's part of the `yum-utils` package, it might be useful in case someone can't or doesn't want to download additional scripts.

The problem with `verifytree` is, while it also does the checksum verification of the packages, it's not well suited for the `reposync` use case since it expects a valid repo with the `repodata/` subdir which `reposync` doesn't create (it just downloads the packages).

In order to have this functionality in `yum-utils` directly, it would probably make more sense to extend the existing scripts (such as `verifytree`) since the logic (downloading, checksumming) is already there to some extent. For example, we could add an option to `reposync` to create and populate the `repodata/` subdir so that it could be easily checked with `verifytree` afterwards, or something like that.

In any case, thanks for sharing `check-rpm`! It looks good and it's certainly the easiest option here at the moment.

**Comment by rothgar** [comment] 2018-06-06 17:46
Sorry my `check-rpm` script didn't get approved to be open sourced. Hopefully this can be implemented directly in `reposync` in the future.

**Comment by dmnks** [comment] 2020-02-12 14:26
Thank you for the report. However, please note that this project has been deprecated and is no longer maintained upstream. Please consider migrating to [DNF](https://github.com/rpm-software-management/dnf) which is the successor of YUM. That said, I’ll close this issue now.

**Closed as completed by dmnks** 2020-02-12 14:26 UTC
